// <auto-generated />
namespace Alliance_for_Life.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NONRMIupdatedmonth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NONRMIupdatedmonth));
        
        string IMigrationMetadata.Id
        {
            get { return "201906261433544_NONRMIupdatedmonth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
